# Generated by Django 4.2.6 on 2023-10-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoshiqchi',
            name='tugilgan_yil',
            field=models.DateField(),
        ),
    ]
